// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Domain.Models;

public partial class Form
{
    public int FormId { get; set; }

    public int MemberId { get; set; }

    public string Status { get; set; }

    public DateTime CreatedTime { get; set; }

    public DateTime? ModifiredTime { get; set; }

    public DateTime? ClosedTime { get; set; }

    public string Description { get; set; }

    public virtual ICollection<FormTask> FormTask { get; set; } = new List<FormTask>();
}