// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Domain.Models;

public partial class FormTask
{
    public int TaskId { get; set; }

    public string Type { get; set; }

    public string Status { get; set; }

    public int FormId { get; set; }

    public int AssignmentId { get; set; }

    public DateTime ApproveTime { get; set; }

    public string TaskName { get; set; }
}