// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Domain.Models;

public partial class IssueCategories
{
    public int IssueCategoriesId { get; set; }

    public string IssueCategoriesName { get; set; }

    public bool IsProgramIssue { get; set; }

    public bool IsActive { get; set; }

    public DateTime CreatedTime { get; set; }

    public DateTime ModifiedTime { get; set; }

    public virtual ICollection<RelCategoriesProduct> RelCategoriesProduct { get; set; } = new List<RelCategoriesProduct>();

    public virtual ICollection<Rel_User_Categories> Rel_User_Categories { get; set; } = new List<Rel_User_Categories>();
}