// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Domain.Models;

public partial class IssueCategoiries
{
    public int IssueCategoriesId { get; set; }

    public string CategoryName { get; set; }

    public bool IsProgramIssue { get; set; }

    public bool IsActive { get; set; }

    public DateTime CreateTime { get; set; }

    public DateTime ModifiedTime { get; set; }

    public virtual RelCategoriesProduct RelCategoriesProduct { get; set; }
}