// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Domain.Models;

public partial class Log_Rel_User_Categories
{
    public int LogId { get; set; }

    public int UserId { get; set; }

    public int IssueCategoriesId { get; set; }

    public DateTime? ActionTime { get; set; }

    public int? ActionBy { get; set; }

    public string ActionType { get; set; }
}