// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Domain.Models;

public partial class Member
{
    public int UserId { get; set; }

    public string Username { get; set; }

    public string Password { get; set; }

    public bool IsVip { get; set; }

    public DateTime CreatedTime { get; set; }

    public DateTime ModifiedTime { get; set; }

    public virtual ICollection<Word> Word { get; set; } = new List<Word>();
}