// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Domain.Models;

public partial class Pages
{
    public int PageId { get; set; }

    public string PageUrl { get; set; }

    public DateTime CreatedTime { get; set; }

    public DateTime ModifiedTime { get; set; }

    public bool IsDeleted { get; set; }

    public virtual ICollection<Rel_Page_Role> Rel_Page_Role { get; set; } = new List<Rel_Page_Role>();
}