// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Domain.Models;

public partial class Rel_User_Categories
{
    public int UserId { get; set; }

    public int IssueCategoriesId { get; set; }

    public DateTime CreateTime { get; set; }

    public DateTime ModifiedTime { get; set; }

    public bool IsDeleted { get; set; }

    public virtual IssueCategories IssueCategories { get; set; }

    public virtual User User { get; set; }
}