// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Domain.Models;

public partial class Rel_Page_Role
{
    public int PageId { get; set; }

    public int RoleId { get; set; }

    public DateTime CreateTime { get; set; }

    public DateTime ModifiedTime { get; set; }
}