// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Domain.Models;

public partial class RelCategoriesProduct
{
    public int IssueCategoriesId { get; set; }

    public int ProductId { get; set; }

    public bool IsActive { get; set; }

    public string DeleteFlag { get; set; }

    public DateTime CreatedTime { get; set; }

    public DateTime ModifiedTime { get; set; }

    public virtual IssueCategories IssueCategories { get; set; }

    public virtual Product Product { get; set; }
}