// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Domain.Models;

public partial class Role
{
    public int RoleId { get; set; }

    public string RoleName { get; set; }

    public DateTime CreateTime { get; set; }

    public DateTime ModifiedTime { get; set; }

    public bool IsActive { get; set; }
}