// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Domain.Models;

public partial class SystemConfig
{
    public string ConfigCode { get; set; }

    public string ConfigType { get; set; }

    public string ConfigValue { get; set; }
}