// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Domain.Models;

public partial class Word
{
    public int WordId { get; set; }

    public string Word1 { get; set; }

    public int Score { get; set; }

    public int UserId { get; set; }

    public DateTime CreatedTime { get; set; }

    public DateTime ModifiedTime { get; set; }

    public virtual Member User { get; set; }
}